### ISSUE TITLE
First round comments on abstract

### ISSUE THREAD

**Issue by katyhuff** [arfc/2019-chee-ihlrwm#3]
- This can, and probably should, be a bit longer. (I think you can use 200 more words and remain under the limit).
- You might consider using the ANS summary format for this (the full paper will need to obey it and the reviewers will see many abstracts already in this ANS format). There are .cls, .sty, etc. files in other repositories.
- The abstract currently begins with a potential reason why a reader might think this work is futile (repository challenges are primarily political/social rather than technical). Instead, the first sentence should state why you are doing this work. What are the objectives of the work?
- The motivating sentence and objective should be followed immediately by previous work in the area. (mention/cite cyderv1, mention previous work by others and their conclusions related to last-out-first-in, first-out-last-in, etc.... demonstrate that a question of some kind remains unanswered.)
- You do a good job explaining cyclus agents and the simulaitons you will run. Keep this part, however, don't forget to metion the name and location of the tool you're developing.
- End with a description of the potential applications for this work and its potential findings.
- Is your bibliography somewhere in the zotero paper dev? I'd like to add one or more references to it.

**Comment by gwenchee** [comment]
Thank you for your comments! I'll work on implementing them. 

Yes, I have a bibliography folder named 2019-chee-ihlrwm in zotero.

**Comment by katyhuff** [comment]
great -- I've added some potentially useful papers to that folder. I know you've read some of them before.

**Comment by gwenchee** [comment]
closed with https://github.com/arfc/2019-chee-ihlrwm/pull/4
